db:
  image: postgres
  restart: always
  volumes:
    - ./postgres_data:/var/lib/postgresql/data/pgdata
  environment:
    POSTGRES_PASSWORD: cirf
  ports:
    - '54320:5432'
adminer:
  image: adminer
  restart: always
  ports:
    - 8080:8080
