# Generated by Django 3.1.7 on 2021-02-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscrizioni', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='immagine',
            field=models.ImageField(blank=True, default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='inizio_iscrizioni',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='slug',
            field=models.SlugField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='termine_iscrizioni',
            field=models.DateTimeField(blank=True),
        ),
    ]
