# Generated by Django 3.1.7 on 2021-02-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscrizioni', '0002_auto_20210220_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='immagine',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='evento',
            name='inizio_iscrizioni',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='termine_iscrizioni',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
