# Generated by Django 3.1.7 on 2021-02-20 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iscrizioni', '0003_auto_20210220_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['-inizio_iscrizioni'], 'verbose_name_plural': 'Eventi'},
        ),
    ]
