# Generated by Django 3.1.7 on 2021-02-20 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iscrizioni', '0005_auto_20210220_1714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utente',
            options={'ordering': ['cognome', 'nome'], 'verbose_name': 'Utente registrato', 'verbose_name_plural': 'Utenti registrati'},
        ),
    ]
