# Generated by Django 3.1.7 on 2021-02-20 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iscrizioni', '0006_auto_20210220_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='email_validata',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='utente',
            name='ordine_di_appartenenza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iscrizioni.ordine'),
        ),
        migrations.AlterField(
            model_name='utente',
            name='regione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iscrizioni.regione'),
        ),
        migrations.AlterField(
            model_name='utente',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
