# Generated by Django 3.1.7 on 2021-02-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscrizioni', '0007_auto_20210220_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utente',
            name='accettazione_privacy',
            field=models.BooleanField(),
        ),
    ]
