# Generated by Django 3.1.7 on 2021-02-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscrizioni', '0008_auto_20210220_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utente',
            name='accettazione_privacy',
            field=models.BooleanField(default=False),
        ),
    ]
