# Generated by Django 3.1.7 on 2021-02-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscrizioni', '0009_auto_20210220_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='telefono',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
