# Generated by Django 3.1.7 on 2021-02-20 17:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscrizioni', '0010_utente_telefono'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iscrizione',
            options={'ordering': ['iscritto__cognome', 'iscritto__nome'], 'verbose_name_plural': 'iscrizioni'},
        ),
        migrations.AlterModelOptions(
            name='utente',
            options={'ordering': ['cognome', 'nome'], 'verbose_name': 'utente registrato', 'verbose_name_plural': 'utenti registrati'},
        ),
        migrations.AlterField(
            model_name='iscrizione',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='iscrizione',
            name='importo_ricevuto',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
    ]
