# Generated by Django 3.1.7 on 2021-02-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscrizioni', '0011_auto_20210220_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='slug',
            field=models.SlugField(blank=True, max_length=30, unique=True),
        ),
    ]
