# Generated by Django 3.1.7 on 2021-02-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscrizioni', '0012_auto_20210220_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='richiede_autenticazione',
            field=models.BooleanField(default=False, help_text="spuntare questa casella se si desidera che l'utente possa accedere a una pagina dove potrà gestire la propria iscrizione, ad esempio per inviare un abstract"),
        ),
    ]
