# Generated by Django 3.1.7 on 2021-02-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscrizioni', '0016_auto_20210221_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utente',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AddConstraint(
            model_name='iscrizione',
            constraint=models.UniqueConstraint(fields=('iscritto', 'evento'), name='iscrizione_ad_evento'),
        ),
    ]
