# Generated by Django 3.1.7 on 2021-02-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscrizioni', '0019_auto_20210221_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='testo_link',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
