# Generated by Django 3.1.7 on 2021-02-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscrizioni', '0020_evento_testo_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accreditamentoordine',
            options={'verbose_name_plural': 'accreditamenti ordini'},
        ),
        migrations.AlterField(
            model_name='accreditamentoordine',
            name='istruzioni',
            field=models.TextField(blank=True, help_text="il testo verrà inserito nell'email di conferma iscrizione ed eventualmente ripetuto in email successive solo per gli utenti iscritti a questo evento e appartenenti a quest'ordine professionale."),
        ),
    ]
