# Generated by Django 3.1.7 on 2021-02-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscrizioni', '0021_auto_20210221_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accreditamentoordine',
            name='regione',
            field=models.CharField(blank=True, choices=[('Abruzzo', 'Abruzzo'), ('Basilicata', 'Basilicata'), ('Calabria', 'Calabria'), ('Campania', 'Campania'), ('Emilia-Romagna', 'Emilia Romagna'), ('Friuli-Venezia Giulia', 'Friuli Venezia Giulia'), ('Lazio', 'Lazio'), ('Liguria', 'Liguria'), ('Lombardia', 'Lombardia'), ('Marche', 'Marche'), ('Molise', 'Molise'), ('Piemonte', 'Piemonte'), ('Puglia', 'Puglia'), ('Sardegna', 'Sardegna'), ('Sicilia', 'Sicilia'), ('Toscana', 'Toscana'), ('Trentino-Alto Adige', 'Trentino Alto Adige'), ('Umbria', 'Umbria'), ("Valle d'Aosta", 'Valle D Aosta'), ('Veneto', 'Veneto')], help_text='lasciare vuoto per indicare tutte le regioni', max_length=21),
        ),
    ]
