# Generated by Django 3.1.7 on 2021-02-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscrizioni', '0022_auto_20210221_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='istruzioni_email',
            field=models.TextField(blank=True, help_text="Inserire un testo che apparirà nell'email di conferma dell'iscrizione all'evento (opzionale)"),
        ),
    ]
