# Generated by Django 3.1.7 on 2021-02-24 10:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscrizioni', '0024_auto_20210224_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='attivita',
            name='crediti_riconosciuti',
            field=models.BooleanField(default=True, help_text='I crediti verranno riconosciuti solo se sono previsti anche a livello di evento. Normalmente è sicuro lasciare questa casella spuntata.'),
        ),
        migrations.AddField(
            model_name='attivita',
            name='istruzioni_email',
            field=models.TextField(blank=True, help_text="Inserire un testo che apparirà nell'email di conferma dell'iscrizione all'evento (opzionale)"),
        ),
        migrations.AlterField(
            model_name='attivita',
            name='descrizione',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='attivita',
            name='valore_crediti_riconosciuti',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('1'), max_digits=5),
        ),
    ]
