# Generated by Django 3.1.7 on 2021-02-24 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iscrizioni', '0025_auto_20210224_1051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attivita',
            options={'verbose_name': 'attività', 'verbose_name_plural': 'attività'},
        ),
        migrations.AlterModelOptions(
            name='partecipazioneattivita',
            options={'verbose_name': 'iscrizione singola attività', 'verbose_name_plural': 'iscrizioni singola attività'},
        ),
    ]
