# Generated by Django 3.1.7 on 2021-02-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscrizioni', '0027_auto_20210224_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='attivita',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='attivita',
            name='mostra_link_nel_modulo_iscrizione',
            field=models.BooleanField(default=False, help_text='mostrandolo nel modulo di iscrizione, sarà accessibile a tutti, anche i non iscritti. Normalmente è bene che non sia spuntata questa casella.'),
        ),
        migrations.AddField(
            model_name='attivita',
            name='testo_link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='attivita',
            name='tipo_attivita',
            field=models.CharField(choices=[('seminario', 'Seminario'), ('workshop', 'Workshop'), ('webinar', 'Webinar'), ('pranzo_sociale', 'Pranzo sociale'), ('field_trip', 'Field trip')], default='seminario', max_length=20),
        ),
        migrations.AlterField(
            model_name='attivita',
            name='istruzioni_email',
            field=models.TextField(blank=True, help_text="Inserire un testo che apparirà nell'email di conferma dell'iscrizione all'evento (opzionale). Può essere usata per indicare la password del webinar. Per il link invece usare l'apposita casella qui sotto."),
        ),
    ]
