# Generated by Django 3.1.7 on 2021-02-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscrizioni', '0028_auto_20210224_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attivita',
            name='inizio_attivita',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attivita',
            name='termine_attivita',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
