# Generated by Django 3.1.7 on 2021-02-24 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iscrizioni', '0029_auto_20210224_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partecipazioneattivita',
            name='iscritto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iscrizioni.iscrizione'),
        ),
    ]
