# Generated by Django 3.1.7 on 2021-02-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscrizioni', '0031_auto_20210224_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='attivita',
            name='ordine',
            field=models.IntegerField(blank=True, default=0, help_text="Se due attività hanno la stessa data/ora, mostra prima quella che avrà il valore 'ordine' più basso."),
        ),
    ]
