# Generated by Django 3.1.7 on 2021-05-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscrizioni', '0033_evento_istruzioni_finali'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='modello_form_evento',
            field=models.CharField(choices=[('default', 'Default'), ('no_ordine', "Senza richiesta informazioni iscrizione all'ordine"), ('con_attivita', 'Con selezione attività')], default='default', max_length=20),
        ),
    ]
