# Generated by Django 3.1.7 on 2022-04-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscrizioni', '0034_auto_20210518_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='crediti_riconosciuti',
            field=models.BooleanField(default=True, help_text='Se sono previsti crediti per questo evento, spuntare questa casella.'),
        ),
        migrations.AlterField(
            model_name='attivita',
            name='opzionale',
            field=models.BooleanField(default=True, help_text="Se spuntato, permetterà all'utente di iscriversi all'attività. Se rimane vuoto allora diventa obbligatorio e non apparirà alcuna possibilità di selezionare: si dà per scontato che l'utente partecipi in ogni caso."),
        ),
    ]
