# Generated by Django 3.1.7 on 2022-06-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscrizioni', '0035_auto_20220414_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='attivita',
            name='link_evento_avvenuto',
            field=models.URLField(blank=True, help_text="link da mostrare nell'email di iscrizione se l'evento ha già avuto luogo. Ad esempio può rimandare al video del webinar.", null=True),
        ),
        migrations.AddField(
            model_name='attivita',
            name='testo_link_evento_avvenuto',
            field=models.CharField(blank=True, help_text="Testo da mostrare nell'email di iscrizione se l'evento ha già avuto luogo. Ad esempio: 'Registrazione dell'evento'.", max_length=100, null=True),
        ),
    ]
