# Generated by Django 3.1.7 on 2022-06-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscrizioni', '0036_auto_20220613_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attivita',
            name='testo_link_evento_avvenuto',
            field=models.CharField(blank=True, default="Informazioni sull'evento", help_text="Testo da mostrare nell'email di iscrizione se l'evento ha già avuto luogo. Ad esempio: 'Registrazione dell'evento'.", max_length=100, null=True),
        ),
    ]
