version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: cirf
    ports:
      - '54320:5432'
    labels:
      it.iloa.container_prefix: '${APP_NAME}'
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    labels:
      it.iloa.container_prefix: '${APP_NAME}'
